language: ruby
rvm:
- 2.2
before_script:
script:
- bundle exec jekyll build --config _config.yml,_config_gh_pages.yml
after_success:
- echo "Pull request number - ${TRAVIS_PULL_REQUEST}"
- echo "Target branch name - ${TRAVIS_BRANCH}"
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'master' ]; then
  chmod +x ./scripts/deploy;
  source scripts/deploy;
  fi;
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/mvlabat/ark-gsoc-2016.git
  - REPO_TARGET_BRANCH: gh-pages
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c22f5515b365447ab012
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
