#!/usr/bin/env bash

git clone -b gh-pages --single-branch https://$GITHUB_REPO

cd $(basename ${GITHUB_REPO%.git})
git config user.name "Travis CI"
git config user.email ${EMAIL}
rsync -az --delete --exclude '.git*' ../_site/ .
touch .nojekyll
git add -A .
git commit -m "Pull request: ${TRAVIS_PULL_REQUEST}. Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
git push "https://${GITHUB_TOKEN}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH} 2>&1 | sed -e "s/${GITHUB_TOKEN}/[you won't see this :p]/g"
